package models;

import java.math.BigDecimal;

/**
 * RestaurantAnalytics class
 * 
 * This class is a model (POJO - Plain Old Java Object) used to store
 * analytical data related to a restaurant.
 * 
 * It typically represents aggregated data such as:
 * - Total number of orders
 * - Total revenue generated
 * 
 * This class is often used in reporting, dashboards, or analytics features.
 */
public class RestaurantAnalytics {

    // Unique identifier of the restaurant
    private int restaurantId;

    // Name of the restaurant
    private String restaurantName;

    // Total number of orders placed for this restaurant
    private int totalOrders;

    // Total revenue generated by the restaurant
    // BigDecimal is used instead of double for precise financial calculations
    private BigDecimal totalRevenue;

    /**
     * Default constructor
     * 
     * Required for frameworks (e.g., Hibernate, Spring, JSP) 
     * to instantiate the object using reflection.
     */
    public RestaurantAnalytics() {
    }

    /**
     * Get the restaurant ID
     * 
     * @return restaurantId
     */
    public int getRestaurantId() {
        return restaurantId;
    }

    /**
     * Set the restaurant ID
     * 
     * @param restaurantId - unique identifier of the restaurant
     */
    public void setRestaurantId(int restaurantId) {
        this.restaurantId = restaurantId;
    }

    /**
     * Get the restaurant name
     * 
     * @return restaurantName
     */
    public String getRestaurantName() {
        return restaurantName;
    }

    /**
     * Set the restaurant name
     * 
     * @param restaurantName - name of the restaurant
     */
    public void setRestaurantName(String restaurantName) {
        this.restaurantName = restaurantName;
    }

    /**
     * Get total number of orders
     * 
     * @return totalOrders
     */
    public int getTotalOrders() {
        return totalOrders;
    }

    /**
     * Set total number of orders
     * 
     * @param totalOrders - number of orders placed
     */
    public void setTotalOrders(int totalOrders) {
        this.totalOrders = totalOrders;
    }

    /**
     * Get total revenue
     * 
     * @return totalRevenue (BigDecimal for accuracy in monetary values)
     */
    public BigDecimal getTotalRevenue() {
        return totalRevenue;
    }

    /**
     * Set total revenue
     * 
     * @param totalRevenue - total money earned by the restaurant
     */
    public void setTotalRevenue(BigDecimal totalRevenue) {
        this.totalRevenue = totalRevenue;
    }
}